stages:
  - deploy

default:
  tags:
    - group-5

helm:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - export KUBECONFIG=$config
    - cd airflow/
  script:
    - helm upgrade --install airflow apache-airflow/airflow --namespace group-5 --create-namespace -f values.yaml
  rules:
    - changes:
      - airflow/values.yaml
