image: docker:latest

stages:
  - build

before_script:
  - docker run --rm -t -e DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME -e DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD -v /var/run/docker.sock:/var/run/docker.sock docker:latest sh -c "echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin"

build_api:
  stage: build
  script:
    - export IMAGE_NAME="index.docker.io/oleksiihavryliuk/pm-api"
    - docker build --pull -t "$IMAGE_NAME" --label "maintainer=$GITLAB_USER_NAME" .
    - docker tag $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  tags:
    - group-5
  when: manual
