stages:
  - deploy

default:
  tags:
    - group-5

helm:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - export KUBECONFIG=${config}
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - cd airflow/
    - apk add --no-cache aws-cli
  script:
    - helm upgrade --install airflow apache-airflow/airflow --namespace group-5 --create-namespace -f values.yaml --kubeconfig ${config}
  rules:
    - changes:
      - airflow/values.yaml
