stages:
  - deploy

default:
  tags:
    - group-5

helm:
  stage: deploy
  image: pilovetsdanylo/aws-helm-k8s
  before_script:
    - export KUBECONFIG=${config}
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - aws eks update-kubeconfig --name pmacademy
    - cd airflow/
  script:
    - helm repo add apache-airflow https://airflow.apache.org/
    - helm upgrade --install airflow apache-airflow/airflow --namespace group-5 --create-namespace -f values.yaml
  rules:
    - changes:
      - airflow/values.yaml
