stages:
  - deploy

default:
  tags:
    - group-5

helm:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - export KUBECONFIG=$config
  script:
    - helm upgrade airflow apache-airflow/airflow --namespace  group-5 -f values.yaml
  rules:
    - changes:
      - airflow/values.yaml
