output "id" {
  value       = aws_db_instance.this.id
  description = "The database instance ID"
}

output "hosted_zone_id" {
  value       = aws_db_instance.this.hosted_zone_id
  description = "The zone ID for the autogenerated DNS name given in endpoint"
}

output "hostname" {
  value       = aws_db_instance.this.address
  description = "Public DNS name of database instance"
}

output "endpoint" {
  value       = aws_db_instance.this.endpoint
  description = "Public DNS name and port separated by a colon"
}

output "availability_zone" {
  value       = aws_db_instance.this.availability_zone
  description = "The availability zone of the instance"
}
